services:
  redis:
    image: redis:alpine
    command:
      - redis-server
      - /redis.conf
      - --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/redis.conf
      - ./data:/data